[colors]
  [colors.primary]
  background = "#232136"
  foreground = "#f2e9e1"

  [colors.cursor]
  text = "#e0def4"
  cursor = "#908caa"

  [colors.line_indicator]
  foreground = "None"
  background = "None"

  [colors.selection]
  text = "#e0def4"
  background = "#44415a"

  [colors.normal]
  black = "#393552"
  red = "#eb6f92"
  green = "#3e8fb0"
  yellow = "#f6c177"
  blue = "#9ccfd8"
  magenta = "#c4a7e7"
  cyan = "#ea9a97"
  white = "#f2e9e1"

  [colors.bright]
  black = "#6e6a86"
  red = "#eb6f92"
  green = "#3e8fb0"
  yellow = "#f6c177"
  blue = "#9ccfd8"
  magenta = "#c4a7e7"
  cyan = "#ea9a97"
  white = "#e0def4"

  [colors.hints.start]
  foreground = "#908caa"
  background = "#2a273f"

  [colors.hints.end]
  foreground = "#6e6a86"
  background = "#2a273f"
